version: 2.0
jobs:
    
    "mxnet-py37-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:mxnet-py37-cpu -f docker/Dockerfile.mxnet-py37-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:mxnet-py37-cpu
    
    "cntk-py37-cu100":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:cntk-py37-cu100 -f docker/Dockerfile.cntk-py37-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:cntk-py37-cu100
    
    "sonnet-py37-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:sonnet-py37-cpu -f docker/Dockerfile.sonnet-py37-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:sonnet-py37-cpu
    
    "all-py37-cu100_py37-cu100":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:all-py37-cu100 -t $DOCKER_REPO:py37-cu100 -f docker/Dockerfile.all-py37-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:all-py37-cu100            
            - run: docker push $DOCKER_REPO:py37-cu100
    
    "tensorflow-py37-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:tensorflow-py37-cpu -f docker/Dockerfile.tensorflow-py37-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:tensorflow-py37-cpu
    
    "all-py37-cpu_py37-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:all-py37-cpu -t $DOCKER_REPO:py37-cpu -f docker/Dockerfile.all-py37-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:all-py37-cpu            
            - run: docker push $DOCKER_REPO:py37-cpu
    
    "pytorch-py37-cu100":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:pytorch-py37-cu100 -f docker/Dockerfile.pytorch-py37-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:pytorch-py37-cu100
    
    "darknet-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:darknet-cpu -f docker/Dockerfile.darknet-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:darknet-cpu
    
    "lasagne-py37-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:lasagne-py37-cpu -f docker/Dockerfile.lasagne-py37-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:lasagne-py37-cpu
    
    "tensorflow-py37-cu100":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:tensorflow-py37-cu100 -f docker/Dockerfile.tensorflow-py37-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:tensorflow-py37-cu100
    
    "sonnet-py37-cu100":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:sonnet-py37-cu100 -f docker/Dockerfile.sonnet-py37-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:sonnet-py37-cu100
    
    "darknet-cu100":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:darknet-cu100 -f docker/Dockerfile.darknet-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:darknet-cu100
    
    "chainer-py37-cu100":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:chainer-py37-cu100 -f docker/Dockerfile.chainer-py37-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:chainer-py37-cu100
    
    "keras-py37-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:keras-py37-cpu -f docker/Dockerfile.keras-py37-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:keras-py37-cpu
    
    "theano-py37-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:theano-py37-cpu -f docker/Dockerfile.theano-py37-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:theano-py37-cpu
    
    "keras-py37-cu100":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:keras-py37-cu100 -f docker/Dockerfile.keras-py37-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:keras-py37-cu100
    
    "chainer-py37-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:chainer-py37-cpu -f docker/Dockerfile.chainer-py37-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:chainer-py37-cpu
    
    "cntk-py37-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:cntk-py37-cpu -f docker/Dockerfile.cntk-py37-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:cntk-py37-cpu
    
    "torch-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:torch-cpu -f docker/Dockerfile.torch-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:torch-cpu
    
    "all-jupyter-py37-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:all-jupyter-py37-cpu -f docker/Dockerfile.all-jupyter-py37-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:all-jupyter-py37-cpu
    
    "lasagne-py37-cu100":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:lasagne-py37-cu100 -f docker/Dockerfile.lasagne-py37-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:lasagne-py37-cu100
    
    "mxnet-py37-cu100":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:mxnet-py37-cu100 -f docker/Dockerfile.mxnet-py37-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:mxnet-py37-cu100
    
    "torch-cu100":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:torch-cu100 -f docker/Dockerfile.torch-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:torch-cu100
    
    "pytorch-py37-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:pytorch-py37-cpu -f docker/Dockerfile.pytorch-py37-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:pytorch-py37-cpu
    
    "all-jupyter-py37-cu100":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:all-jupyter-py37-cu100 -f docker/Dockerfile.all-jupyter-py37-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:all-jupyter-py37-cu100
    
    "caffe-py37-cu100":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:caffe-py37-cu100 -f docker/Dockerfile.caffe-py37-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:caffe-py37-cu100
    
    "caffe-py37-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:caffe-py37-cpu -f docker/Dockerfile.caffe-py37-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:caffe-py37-cpu
    
    "theano-py37-cu100":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:theano-py37-cu100 -f docker/Dockerfile.theano-py37-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:theano-py37-cu100

workflows:
    version: 2
    build:
        jobs:
            - "mxnet-py37-cpu"
            - "cntk-py37-cu100"
            - "sonnet-py37-cpu"
            - "all-py37-cu100_py37-cu100"
            - "tensorflow-py37-cpu"
            - "all-py37-cpu_py37-cpu"
            - "pytorch-py37-cu100"
            - "darknet-cpu"
            - "lasagne-py37-cpu"
            - "tensorflow-py37-cu100"
            - "sonnet-py37-cu100"
            - "darknet-cu100"
            - "chainer-py37-cu100"
            - "keras-py37-cpu"
            - "theano-py37-cpu"
            - "keras-py37-cu100"
            - "chainer-py37-cpu"
            - "cntk-py37-cpu"
            - "torch-cpu"
            - "all-jupyter-py37-cpu"
            - "lasagne-py37-cu100"
            - "mxnet-py37-cu100"
            - "torch-cu100"
            - "pytorch-py37-cpu"
            - "all-jupyter-py37-cu100"
            - "caffe-py37-cu100"
            - "caffe-py37-cpu"
            - "theano-py37-cu100"