version: 2.0
jobs:
    
    "mxnet-py36-cpu_mxnet-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:mxnet-py36-cpu -t $DOCKER_REPO:mxnet-cpu -f docker/Dockerfile.mxnet-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:mxnet-py36-cpu            
            - run: docker push $DOCKER_REPO:mxnet-cpu
    
    "tensorflow-py36-cpu_tensorflow-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:tensorflow-py36-cpu -t $DOCKER_REPO:tensorflow-cpu -f docker/Dockerfile.tensorflow-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:tensorflow-py36-cpu            
            - run: docker push $DOCKER_REPO:tensorflow-cpu
    
    "sonnet-py36-cpu_sonnet-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:sonnet-py36-cpu -t $DOCKER_REPO:sonnet-cpu -f docker/Dockerfile.sonnet-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:sonnet-py36-cpu            
            - run: docker push $DOCKER_REPO:sonnet-cpu
    
    "chainer-py36-cu100":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:chainer-py36-cu100 -f docker/Dockerfile.chainer-py36-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:chainer-py36-cu100
    
    "keras-py36-cu100":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:keras-py36-cu100 -f docker/Dockerfile.keras-py36-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:keras-py36-cu100
    
    "all-py36-cpu_all-cpu_py36-cpu_cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:all-py36-cpu -t $DOCKER_REPO:all-cpu -t $DOCKER_REPO:py36-cpu -t $DOCKER_REPO:cpu -f docker/Dockerfile.all-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:all-py36-cpu            
            - run: docker push $DOCKER_REPO:all-cpu            
            - run: docker push $DOCKER_REPO:py36-cpu            
            - run: docker push $DOCKER_REPO:cpu
    
    "darknet-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:darknet-cpu -f docker/Dockerfile.darknet-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:darknet-cpu
    
    "darknet-cu100":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:darknet-cu100 -f docker/Dockerfile.darknet-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:darknet-cu100
    
    "lasagne-py36-cpu_lasagne-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:lasagne-py36-cpu -t $DOCKER_REPO:lasagne-cpu -f docker/Dockerfile.lasagne-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:lasagne-py36-cpu            
            - run: docker push $DOCKER_REPO:lasagne-cpu
    
    "cntk-py36-cu100":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:cntk-py36-cu100 -f docker/Dockerfile.cntk-py36-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:cntk-py36-cu100
    
    "all-py36-cu100_py36-cu100":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:all-py36-cu100 -t $DOCKER_REPO:py36-cu100 -f docker/Dockerfile.all-py36-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:all-py36-cu100            
            - run: docker push $DOCKER_REPO:py36-cu100
    
    "tensorflow-py36-cu100":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:tensorflow-py36-cu100 -f docker/Dockerfile.tensorflow-py36-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:tensorflow-py36-cu100
    
    "sonnet-py36-cu100":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:sonnet-py36-cu100 -f docker/Dockerfile.sonnet-py36-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:sonnet-py36-cu100
    
    "keras-py36-cpu_keras-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:keras-py36-cpu -t $DOCKER_REPO:keras-cpu -f docker/Dockerfile.keras-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:keras-py36-cpu            
            - run: docker push $DOCKER_REPO:keras-cpu
    
    "theano-py36-cpu_theano-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:theano-py36-cpu -t $DOCKER_REPO:theano-cpu -f docker/Dockerfile.theano-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:theano-py36-cpu            
            - run: docker push $DOCKER_REPO:theano-cpu
    
    "pytorch-py36-cu100":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:pytorch-py36-cu100 -f docker/Dockerfile.pytorch-py36-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:pytorch-py36-cu100
    
    "all-jupyter-py36-cu100":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:all-jupyter-py36-cu100 -f docker/Dockerfile.all-jupyter-py36-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:all-jupyter-py36-cu100
    
    "chainer-py36-cpu_chainer-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:chainer-py36-cpu -t $DOCKER_REPO:chainer-cpu -f docker/Dockerfile.chainer-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:chainer-py36-cpu            
            - run: docker push $DOCKER_REPO:chainer-cpu
    
    "all-jupyter-py36-cpu_all-jupyter-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:all-jupyter-py36-cpu -t $DOCKER_REPO:all-jupyter-cpu -f docker/Dockerfile.all-jupyter-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:all-jupyter-py36-cpu            
            - run: docker push $DOCKER_REPO:all-jupyter-cpu
    
    "torch-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:torch-cpu -f docker/Dockerfile.torch-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:torch-cpu
    
    "mxnet-py36-cu100":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:mxnet-py36-cu100 -f docker/Dockerfile.mxnet-py36-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:mxnet-py36-cu100
    
    "cntk-py36-cpu_cntk-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:cntk-py36-cpu -t $DOCKER_REPO:cntk-cpu -f docker/Dockerfile.cntk-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:cntk-py36-cpu            
            - run: docker push $DOCKER_REPO:cntk-cpu
    
    "theano-py36-cu100":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:theano-py36-cu100 -f docker/Dockerfile.theano-py36-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:theano-py36-cu100
    
    "caffe-py36-cu100":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:caffe-py36-cu100 -f docker/Dockerfile.caffe-py36-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:caffe-py36-cu100
    
    "torch-cu100":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:torch-cu100 -f docker/Dockerfile.torch-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:torch-cu100
    
    "pytorch-py36-cpu_pytorch-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:pytorch-py36-cpu -t $DOCKER_REPO:pytorch-cpu -f docker/Dockerfile.pytorch-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:pytorch-py36-cpu            
            - run: docker push $DOCKER_REPO:pytorch-cpu
    
    "lasagne-py36-cu100":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:lasagne-py36-cu100 -f docker/Dockerfile.lasagne-py36-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:lasagne-py36-cu100
    
    "caffe-py36-cpu_caffe-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:caffe-py36-cpu -t $DOCKER_REPO:caffe-cpu -f docker/Dockerfile.caffe-py36-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:caffe-py36-cpu            
            - run: docker push $DOCKER_REPO:caffe-cpu

workflows:
    version: 2
    build:
        jobs:
            - "mxnet-py36-cpu_mxnet-cpu"
            - "tensorflow-py36-cpu_tensorflow-cpu"
            - "sonnet-py36-cpu_sonnet-cpu"
            - "chainer-py36-cu100"
            - "keras-py36-cu100"
            - "all-py36-cpu_all-cpu_py36-cpu_cpu"
            - "darknet-cpu"
            - "darknet-cu100"
            - "lasagne-py36-cpu_lasagne-cpu"
            - "cntk-py36-cu100"
            - "all-py36-cu100_py36-cu100"
            - "tensorflow-py36-cu100"
            - "sonnet-py36-cu100"
            - "keras-py36-cpu_keras-cpu"
            - "theano-py36-cpu_theano-cpu"
            - "pytorch-py36-cu100"
            - "all-jupyter-py36-cu100"
            - "chainer-py36-cpu_chainer-cpu"
            - "all-jupyter-py36-cpu_all-jupyter-cpu"
            - "torch-cpu"
            - "mxnet-py36-cu100"
            - "cntk-py36-cpu_cntk-cpu"
            - "theano-py36-cu100"
            - "caffe-py36-cu100"
            - "torch-cu100"
            - "pytorch-py36-cpu_pytorch-cpu"
            - "lasagne-py36-cu100"
            - "caffe-py36-cpu_caffe-cpu"